apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: contoso-traders-products
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3 # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contoso-traders-product
  targetCPUUtilizationPercentage: 5 # target CPU utilization
